# Dockerfile for Node Express Backend api (development)

FROM node:slim

# Create App Directory
RUN mkdir -p /opt/accsm/code
WORKDIR /opt/accsm

# Install Dependencies
COPY package*.json ./
RUN npm install --no-optional && npm cache clean --force
ENV PATH /opt/accsm/node_modules/.bin:$PATH

# Copy app source code
WORKDIR /opt/accsm/code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "devStart"]
