# Dockerfile for Node Express Backend api (development)

FROM node:slim

# Create App Directory
RUN mkdir -p /opt/accsm/code
WORKDIR /opt/accsm

# Install Dependencies
COPY package*.json ./
RUN npm ci --quiet
ENV PATH /opt/accsm/node_modules/.bin:$PATH

# Copy app source code
WORKDIR /opt/accsm/code
COPY . .

EXPOSE 3000

CMD ["nodemon", "-L", "server.js"]
