version: '3.9'

services:
  node:
    container_name: accsm-node
    build:
      context: server/.
      dockerfile: ../docker/server/Dockerfile.dev
    command: bash -c "rm -rf /opt/accsm/code/node_modules/* && nodemon -L server.js"
    restart: always
    networks:
      - accsm-network
    ports:
      - '$SERVER_PORT:$SERVER_PORT'
    volumes:
      - ./server/:/opt/accsm/code
      - accsm-node_modules:/opt/accsm/code/node_modules
    environment:
      - PORT=${SERVER_PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo

  mongo:
    container_name: accsm-mongo
    build:
      context: docker/database/.
      dockerfile: Dockerfile
    command: [--auth]
    restart: always
    networks:
      - accsm-network
    ports:
      - '$MONGO_PORT:$MONGO_PORT'
    volumes:
      - .database:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_APPDB_PASSWORD=${MONGO_APPDB_PASSWORD}
      - MONGO_APPDB_USERNAME=${MONGO_APPDB_USERNAME}

networks:
  accsm-network:
    name: accsm-network
    driver: bridge

volumes:
  accsm-node_modules:
