version: '3.9'

services:
  server:
    container_name: accsm-server
    build:
      context: server/.
      dockerfile: ../docker/server/Dockerfile.dev
    command: npm run devStart
    restart: always
    networks:
      - accsm-network
    ports:
      - '$SERVER_PORT:$SERVER_PORT'
    volumes:
      - ./server/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - PORT=${SERVER_PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    container_name: accsm-mongodb
    build:
      context: docker/database/.
      dockerfile: Dockerfile
    command: [--auth]
    restart: always
    networks:
      - accsm-network
    ports:
      - '$MONGO_PORT:$MONGO_PORT'
    volumes:
      - .database:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_APPDB_PASSWORD=${MONGO_APPDB_PASSWORD}
      - MONGO_APPDB_USERNAME=${MONGO_APPDB_USERNAME}

networks:
  accsm-network:
    name: accsm-network
    driver: bridge

volumes:
  node_modules:
