version: '3.8'

services:
  server:
    build:
      context: ./server/.
      dockerfile: Dockerfile.dev
    container_name: accsm-server
    command: npm run devStart
    volumes:
      - ./server/:/usr/src/app
    networks:
      - accsm-network
    ports:
      - '3000:3000'
    links:
      - mongo
    restart: always

  mongo:
    image: mongo
    container_name: accsm-mongodb
    networks:
      - accsm-network
    ports:
      - '27017:27017'
    volumes:
      - .database:/data/db
    restart: always

networks:
  accsm-network:
    name: accsm-network
    driver: bridge
