version: '3.9'

services:
  nginx:
    container_name: accsm-nginx
    restart: always
    build:
      context: docker/nginx/.
      dockerfile: Dockerfile.dev
    networks:
      - accsm-network
    ports:
      - '8080:80'
    links:
      - react:react
      - node:node

  react:
    container_name: accsm-react
    build:
      context: client/.
      dockerfile: ../docker/client/Dockerfile.dev
    command: ash -c "rm -rf /opt/accsm/code/node_models/* && npm run start"
    restart: always
    stdin_open: true
    networks:
      - accsm-network
    ports:
      - '$REACT_PORT:$REACT_PORT'
    volumes:
      - ./client/:/opt/accsm/code
      - accsm-frontend-node_modules:/opt/accsm/code/node_modules
    environment:
      - BROWSER=none

  node:
    container_name: accsm-node
    build:
      context: server/.
      dockerfile: ../docker/server/Dockerfile.dev
    command: ash -c "rm -rf /opt/accsm/code/node_modules/* && nodemon -L server.js"
    restart: always
    networks:
      - accsm-network
    ports:
      - '$SERVER_PORT'
    volumes:
      - ./server/:/opt/accsm/code
      - accsm-backend-node_modules:/opt/accsm/code/node_modules
    environment:
      - PORT=${SERVER_PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    links:
      - mongo:mongo
    depends_on:
      - 'mongo'

  mongo:
    container_name: accsm-mongo
    build:
      context: docker/database/.
      dockerfile: Dockerfile
    command: [--auth]
    restart: always
    networks:
      - accsm-network
    ports:
      - '$MONGO_PORT:$MONGO_PORT'
    volumes:
      - .database:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_APP_PASSWORD=${MONGO_INITDB_APP_PASSWORD}
      - MONGO_INITDB_APP_USERNAME=${MONGO_INITDB_APP_USERNAME}

networks:
  accsm-network:
    name: accsm-network
    driver: bridge

volumes:
  accsm-backend-node_modules:
  accsm-frontend-node_modules:
