version: '3.9'

services:
  nginx:
    container_name: accsm-nginx
    restart: always
    build:
      context: docker/nginx/.
      dockerfile: Dockerfile
    networks:
      - accsm-network
    ports:
      - '80:80'
    links:
      - react:react
      - express:express

  react:
    container_name: accsm-react
    build:
      context: client/.
      dockerfile: ../docker/client/Dockerfile
    command: ash -c "rm -rf /opt/accsm/code/node_models/* && npm run start"
    restart: always
    stdin_open: true
    networks:
      - accsm-network
    ports:
      - '4200'
    volumes:
      - ./client/:/opt/accsm/code
      - accsm-frontend-node_modules:/opt/accsm/code/node_modules
    environment:
      - BROWSER=none
      - CHOKIDAR_USEPOLLING=true
      - PORT=4200

  express:
    container_name: accsm-express
    build:
      context: server/.
      dockerfile: ../docker/server/Dockerfile
    command: ash -c "rm -rf /opt/accsm/code/node_modules/* && nodemon -L server.js"
    restart: always
    networks:
      - accsm-network
    ports:
      - '5000'
    volumes:
      - ./server/:/opt/accsm/code
      - accsm-backend-node_modules:/opt/accsm/code/node_modules
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - APP_INIT_ADMIN_ACCOUNT=${APP_INIT_ADMIN_ACCOUNT}
      - APP_INIT_ADMIN_PASSWORD=${APP_INIT_ADMIN_PASSWORD}
      - APP_INIT_ADMIN_EMAIL=${APP_INIT_ADMIN_EMAIL}
    links:
      - mongo:mongo
    depends_on:
      - 'mongo'

  mongo:
    container_name: accsm-mongo
    build:
      context: docker/database/.
      dockerfile: Dockerfile
    command: [--auth]
    restart: always
    networks:
      - accsm-network
    ports:
      - '27017:27017'
    volumes:
      - .database:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_APP_PASSWORD=${MONGO_INITDB_APP_PASSWORD}
      - MONGO_INITDB_APP_USERNAME=${MONGO_INITDB_APP_USERNAME}

networks:
  accsm-network:
    name: accsm-network
    driver: bridge

volumes:
  accsm-backend-node_modules:
  accsm-frontend-node_modules:
