# Dockerfile for Node Express Backend api (development)

FROM node:alpine

# Create App Directory
RUN mkdir -p /code
WORKDIR /code

# Install Dependencies
COPY package*.json ./
RUN npm ci

# Copy app source code
COPY . .
