# Dockerfile for Node Express Backend api (development)

FROM node:alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./
RUN npm ci

# Copy app source code
COPY . .

EXPOSE 3000

CMD ["npm", "startDev"]
